Fase 2/Evidencias del proyecto/Evidencias de sistema/naturalworld/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('naturalworld_d.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fase 2/Evidencias del proyecto/Evidencias de sistema/naturalworld_d/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from uuid import UUID

urlpatterns = [
    path('', views.index, name='index'),
    path('producto/<int:producto_id>/', views.producto_detalle, name='producto_detalle'),
    path('producto/<int:producto_id>/crear-preferencia/', views.crear_preferencia, name="crear_preferencia"),
    path('producto/webhook/', views.webhook, name='webhook'),
    path('producto/<int:producto_id>/comentar/', views.agregar_comentario, name="agregar_comentario"),
    path('comentario/<int:comentario_id>/eliminar/', views.eliminar_comentario, name="eliminar_comentario"),
    path('consultar-calles/', views.buscar_calle, name='buscar_calle'),
    path('cotizar-envio/<int:producto_id>/', views.cotizar_envio_view, name='cotizar_envio'),
    path('cobertura-real/', views.cobertura_real_view, name='cobertura_real'),
    path('consultar-calle-numeracion/', views.consultar_calle_numeracion_view, name='consultar_calle_numeracion'),
    path('georreferenciar-direccion/', views.georreferenciar_direccion_view, name='georreferenciar_direccion'),
    path('producto/<int:producto_id>/seleccionar-direccion/', views.seleccionar_direccion, name='seleccionar_direccion'),
    path('producto/<int:producto_id>/calcular-envio/', views.calcular_envio, name='calcular_envio'),
    path('producto/<int:producto_id>/pago/<int:costo_envio>/<int:costo_total>/', views.pago, name='pago'),
    path('producto/<int:producto_id>/crear-preferencia/', views.crear_preferencia, name='crear_preferencia'),
    path('producto/webhook/', views.webhook, name='webhook'),
    path('crear_preferencia/', views.crear_preferencia, name='crear_preferencia'),
    path('agregar_al_carrito/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('ver_carrito/', views.ver_carrito, name='ver_carrito'),
    path('eliminar_del_carrito/<int:producto_id>/', views.eliminar_del_carrito, name='eliminar_del_carrito'),
    path('restar_producto/<int:producto_id>/', views.restar_producto, name='restar_producto'),
    path('limpiar_carrito/', views.limpiar_carrito, name='limpiar_carrito'),
    path('checkout/', views.checkout, name='checkout'),
    path('productos/', views.listar_productos, name='listar_productos'),
    path('pago/', views.pago, name='pago'),
    path('producto/recibir-pago/', views.recibir_pago, name='recibir_pago'),
    path('webhook/', views.webhook, name='webhook'),  # URL para el webhoo
    path('consulta-envio/', views.consultar_envio, name='consulta_envio'),
    path('pag_productos/', views.pag_productos, name='pag_productos'),
    path('buscar/', views.buscar_producto, name='buscar_producto'),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register_view, name='register'),
    path('admin_productos/', views.admin_productos, name='admin_productos'),
    path('admin_pedidos/', views.admin_pedidos, name='admin_pedidos'),
    path('admin_add_producto/', views.admin_add_producto, name='admin_add_producto'),
    path('delete_producto/<id>', views.delete_producto, name="delete_producto"),
    path('admin_mod_producto/<id>', views.admin_mod_producto, name="admin_mod_producto"),
    path('agregar_al_carrito_2/<int:producto_id>/', views.agregar_al_carrito_2, name='agregar_al_carrito_2'),
    path('actualizar_estado_pedido/<uuid:pedido_id>/', views.actualizar_estado_pedido, name='actualizar_estado_pedido'),
    path('mis_pedidos/', views.mis_pedidos, name='mis_pedidos'),
    path('confirmacion/', views.confirmacion, name='confirmacion'),

]

Fase 2/Evidencias del proyecto/Evidencias de sistema/naturalworld_d/models.py
# shipping/models.py

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import uuid
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
import re
from django.conf import settings
from django.db import models, transaction
from decimal import Decimal
# === VALIDADORES ===

def validar_rut(value):
    """
    Valida que el RUT chileno cumpla con el formato correcto.
    """
    pattern = r'^\d{7,8}-[\dkK]$'
    if not re.match(pattern, value):
        raise ValidationError('RUT inválido')

phone_regex = RegexValidator(
    regex=r'^\+?1?\d{9,15}$',
    message="Número de teléfono inválido. Debe tener entre 9 y 15 dígitos."
)

# === MODELOS ===

# === MODELO DE PRODUCTOS ===
class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to="productos", null=False) 
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    descripcion = models.TextField()
    peso = models.DecimalField(max_digits=5, decimal_places=2, help_text="Peso en kg")
    altura = models.IntegerField(help_text="Altura en cm")
    ancho = models.IntegerField(help_text="Ancho en cm")
    largo = models.IntegerField(help_text="Largo en cm")
    
    TIPO_PRODUCTO_CHOICES = [
        ('tipo1', 'Tipo 1'),
        ('tipo2', 'Tipo 2'),
        # Agrega más opciones según sea necesario
    ]
    tipo_producto = models.CharField(max_length=100, choices=TIPO_PRODUCTO_CHOICES, default='tipo1')
    valor_declarado = models.IntegerField(
        null=True, 
        blank=True,
        help_text="Valor declarado del producto"
    )
    stock = models.PositiveIntegerField(default=0)

    def precio_formateado(self):
        return "${:,.0f}".format(self.precio).replace(",", ".")

    def __str__(self):
        return self.nombre

# === MODELO DE CLIENTES ===
class Cliente(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='cliente'
    )
    rut = models.CharField(
        max_length=12,
        null=True,
        blank=True,
        validators=[validar_rut],
        help_text="Formato: 12345678-9"
    )
    email = models.EmailField(unique=True)
    nombre = models.CharField(max_length=100)
    telefono = models.CharField(
        max_length=15,
        null=True,
        blank=True,
        validators=[phone_regex],
        help_text="Formato: +569XXXXXXXX"
    )

    def __str__(self):
        return f"{self.nombre} - {self.rut or 'Sin RUT'}"

    def get_info(self):
        return {
            "rut": self.rut,
            "nombre": self.nombre,
            "email": self.email,
            "telefono": self.telefono,
            "user_id": self.user.id if self.user else None
        }

    @property
    def username(self):
        return self.nombre

# === MODELO DE DIRECCIONES ===
class Direccion(models.Model):
    api_address_id = models.IntegerField(null=True, blank=True)
    county_coverage_code = models.CharField(max_length=4)  # Código de cobertura de la dirección
    street_name = models.CharField(max_length=100)         # Ajustado a 100
    street_number = models.CharField(max_length=10, null=True, blank=True)  # Ajustado a 10
    supplement = models.CharField(max_length=255, null=True, blank=True)
    comuna = models.CharField(max_length=100, default="Desconocido")
    address_type = models.CharField(max_length=4)  # `DEST` o `DEV`
    delivery_on_commercial_office = models.BooleanField(default=False)
    commercial_office_id = models.IntegerField(null=True, blank=True)
    observation = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.street_name} {self.street_number}, {self.county_coverage_code}"

# === MODELO DE CONTACTOS ===
class Contacto(models.Model):
    CONTACT_TYPE_CHOICES = [
        ('R', 'Remitente'),
        ('D', 'Destinatario'),
    ]
    name = models.CharField(max_length=100)
    phone_number = models.CharField(validators=[phone_regex], max_length=15)
    email = models.EmailField()
    contact_type = models.CharField(max_length=1, choices=CONTACT_TYPE_CHOICES)

    def __str__(self):
        return f"{self.name} ({self.get_contact_type_display()})"

# === MODELO DE PEDIDOS ===
# naturalworld_d/models.py

from django.db import models
from django.core.exceptions import ValidationError
import uuid

class Pedido(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    numero_orden = models.CharField(max_length=20, unique=True, blank=True, db_index=True)
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE, null=True, blank=True)
    direccion = models.ForeignKey(
        'Direccion', 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True, 
        related_name='pedidos',
        help_text="Dirección asociada al pedido"
    )
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    # Campos requeridos por la API de Chilexpress
    customer_card_number = models.CharField(
        max_length=12,
        default='18578680',
        help_text="Número de Tarjeta Cliente Chilexpress (TCC). TCC pruebas = 18578680",
        verbose_name="Customer Card Number"
    )  # Obligatorio
    label_type = models.CharField(
        max_length=4,
        choices=[
            ('0', 'Solo Datos'),
            ('1', 'EPL Impresora Zebra + Datos'),
            ('2', 'Imagen en Binario + Datos'),
        ],
        default='2',
        help_text="Tipo de etiqueta; 0 = Solo Datos;1 = EPL Impresora Zebra + Datos;2 = Imagen en Binario + Datos",
        verbose_name="Label Type"
    )  # Obligatorio
    county_of_origin_coverage_code = models.CharField(
        max_length=4,
        help_text="Código de cobertura de origen obtenido por la API Consultar Coberturas",
        verbose_name="County of Origin Coverage Code",
        default='PUDA'  # Valor predeterminado
    )

    estado = models.CharField(
        max_length=20,
        default='pendiente',
    )
    estado_envio = models.CharField(
        max_length=20,
        blank=True,
        null=True,
    )
    numero_seguimiento = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        db_index=True
    )
    servicio_cotizado = models.IntegerField(null=True, blank=True)
    respuesta_envio = models.JSONField(null=True, blank=True)

    # Campos integrados de TransportOrderHeader
    certificate_number = models.BigIntegerField(
        null=True,
        blank=True,
        help_text="Número de certificado, si no se ingresa se creará uno nuevo"
    )
    marketplace_rut = models.CharField(
        max_length=15,
        default='96756430',  # Valor de prueba predeterminado
        help_text="Rut asociado al Marketplace sin puntos ni dígito verificador. RUT pruebas = 96756430",
        verbose_name="Marketplace RUT"
    )
    seller_rut = models.CharField(
        max_length=15,
        default='96756430',  # Valor de prueba predeterminado
        help_text="Rut asociado al Vendedor sin puntos ni dígito verificador. RUT pruebas = 96756430",
        verbose_name="Seller RUT"
    )

    def save(self, *args, **kwargs):
        # Asegurarse de que 'fecha_creacion' esté definida
        if not self.fecha_creacion:
            self.fecha_creacion = timezone.now()

        # Verificar si el número de orden ya está generado
        if not self.numero_orden:
            try:
                fecha_formato = self.fecha_creacion.strftime('%Y%m%d')
                ultimo_pedido = Pedido.objects.filter(
                    fecha_creacion__date=self.fecha_creacion.date()
                ).count() + 1
                self.numero_orden = f"ORD-{fecha_formato}-{ultimo_pedido:04d}"
            except Exception as e:
                raise ValueError(f"Error al generar 'numero_orden': {e}")

        super().save(*args, **kwargs)

    def clean(self):
        """
        Validaciones adicionales antes de guardar.
        """
        if not self.county_of_origin_coverage_code:
            self.county_of_origin_coverage_code = 'PUDA'  # Asignar un valor predeterminado si no lo tiene

        # Validar que los RUTs predeterminados no se usen en producción
        if self.marketplace_rut == '96756430' or self.seller_rut == '96756430':
            if not settings.DEBUG:  # Solo permitir en modo DEBUG
                raise ValidationError("Los RUTs de prueba no deben usarse en producción.")

        super().clean()

    def __str__(self):
        return f"Pedido {self.numero_orden} - Cliente {self.cliente} - Estado {self.estado}"

    @property
    def peso_total(self):
        """
        Calcula el peso total de los productos asociados al pedido.
        """
        return sum(
            detalle.cantidad * detalle.peso_unitario for detalle in self.detalles_pedido.all()
        )


from django.db import models
from decimal import Decimal

class DetallePedido(models.Model):
    pedido = models.ForeignKey(
        'Pedido',
        on_delete=models.CASCADE,
        related_name='detalles_pedido'
    )
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    peso_unitario = models.DecimalField(max_digits=5, decimal_places=2, default=0.0)

    @property
    def subtotal(self):
        """
        Calcula el subtotal del producto dentro del pedido.
        Maneja casos donde 'cantidad' o 'precio_unitario' puedan ser None.
        """
        cantidad = self.cantidad if self.cantidad is not None else 0
        precio_unitario = self.precio_unitario if self.precio_unitario is not None else Decimal('0.00')
        return cantidad * precio_unitario

    def __str__(self):

Fase 2/Evidencias del proyecto/Evidencias de sistema/naturalworld_d/templates/admin_mod_producto.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'img/Logo_principal.png' %}">
    <title>Modificación de producto</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <br>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="form-container">
                    {% if perms.app.add_Producto %}
                    <h2 style=" text-align: center; font-family: 'Arial', sans-serif; background-color: #c5eec8; /* Fondo claro */ padding: 10px 20px; border-radius: 10px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); font-size: 2.5em;">
                        Modificar Producto</h2>
                    <p style="text-align: center; font-size: 120%; margin-top: 20px;"> Completa el siguiente formulario para modificar un producto</p>
                    <form method="POST" action="#" class="needs-validation" id="formulario" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_nombre">Nombre</label>
                            {{ form.nombre }}
                        </div>
                        <div class="form-group">
                            <label for="id_precio">Precio</label>
                            {{ form.precio }}
                        </div>
                        <div class="form-group">
                            <label for="id_descripcion">Descripción</label>
                            {{ form.descripcion }}
                        </div>
                        <div class="form-group">
                            <label for="id_peso">Peso (kg)</label>
                            {{ form.peso }}
                        </div>
                        <div class="form-group">
                            <label for="id_altura">Altura (cm)</label>
                            {{ form.altura }}
                        </div>
                        <div class="form-group">
                            <label for="id_ancho">Ancho (cm)</label>
                            {{ form.ancho }}
                        </div>
                        <div class="form-group">
                            <label for="id_largo">Largo (cm)</label>
                            {{ form.largo }}
                        </div>
                        <div class="form-group">
                            <label for="id_tipo_producto">Tipo de Producto</label>
                            {{ form.tipo_producto }}
                        </div>
                        <div class="form-group">
                            <label for="id_valor_declarado">Valor Declarado</label>
                            {{ form.valor_declarado }}
                        </div>
                        <div class="form-group">
                            <label for="id_stock">Stock</label>
                            {{ form.stock }}
                        </div>

                        <br>
                        <div class="d-flex justify-content-between">
                            <a class="btn btn-outline-success" href="javascript:window.history.back();">Volver Atrás</a>
                            <button type="submit" class="btn btn-success">Modificar Producto</button>
                            
                        </div>
                    </form>
                    {% else %}
                    <br>
                    <p style="text-align: center;">Usted no es un usuario administrador <br> 
                        <a style="color: blue;" href="{% url 'index' %}">Volver al Inicio</a></p>
                    
                    {% endif %}
                    {% if messages %}
                        <div class="mt-3">
                            {% for message in messages %}
                                <div class="alert alert-warning">{{ message }}</div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <br><br><br><br>
</body>
</html>

<script>
(function () {
    'use strict';

    // Obtener el formulario y todos los campos individuales
    var formulario = document.getElementById('formulario');

    formulario.addEventListener('submit', function (event) {
        var esValido = true;

        // Validar campo "Nombre"
        var nombre = document.getElementById('id_nombre');
        if (!nombre.value.trim()) {
            esValido = false;
            nombre.classList.add('is-invalid');
        } else {
            nombre.classList.remove('is-invalid');
        }

        // Validar campo "Precio"
        var precio = document.getElementById('id_precio');
        if (!precio.value || isNaN(precio.value) || parseFloat(precio.value) <= 0) {
            esValido = false;
            precio.classList.add('is-invalid');
        } else {
            precio.classList.remove('is-invalid');
        }

        // Validar campo "Descripción"
        var descripcion = document.getElementById('id_descripcion');
        if (!descripcion.value.trim()) {
            esValido = false;
            descripcion.classList.add('is-invalid');
        } else {
            descripcion.classList.remove('is-invalid');
        }

        // Validar campo "Peso"
        var peso = document.getElementById('id_peso');
        if (!peso.value || isNaN(peso.value) || parseFloat(peso.value) <= 0) {
            esValido = false;
            peso.classList.add('is-invalid');
        } else {
            peso.classList.remove('is-invalid');
        }

        // Validar campos "Altura", "Ancho", "Largo"
        var dimensiones = ['id_altura', 'id_ancho', 'id_largo'];
        dimensiones.forEach(function (campoId) {
            var campo = document.getElementById(campoId);
            if (!campo.value || isNaN(campo.value) || parseFloat(campo.value) <= 0) {
                esValido = false;
                campo.classList.add('is-invalid');
            } else {
                campo.classList.remove('is-invalid');
            }
        });

        // Validar campo "Tipo de Producto"
        var tipoProducto = document.getElementById('id_tipo_producto');
        if (!tipoProducto.value.trim()) {
            esValido = false;
            tipoProducto.classList.add('is-invalid');
        } else {
            tipoProducto.classList.remove('is-invalid');
        }

        // Validar campo "Valor Declarado"
        var valorDeclarado = document.getElementById('id_valor_declarado');
        if (!valorDeclarado.value || isNaN(valorDeclarado.value) || parseFloat(valorDeclarado.value) <= 0) {
            esValido = false;
            valorDeclarado.classList.add('is-invalid');
        } else {
            valorDeclarado.classList.remove('is-invalid');
        }

        // Validar campo "Stock"
        var stock = document.getElementById('id_stock');
        if (!stock.value || isNaN(stock.value) || parseInt(stock.value) < 0) {
            esValido = false;
            stock.classList.add('is-invalid');
        } else {
            stock.classList.remove('is-invalid');
        }

        // Si algún campo no es válido, prevenir el envío
        if (!esValido) {
            event.preventDefault();
            event.stopPropagation();
        }

        formulario.classList.add('was-validated');
    }, false);
})();
</script>


<style>
.form-container {
    border: 2px solid green; /* Borde verde */
    border-radius: 15px; /* Bordes redondeados */
    padding: 20px; /* Espaciado interior */
    background-color: white; /* Fondo blanco */
    box-shadow: 0 0 10px rgba(0, 128, 0, 0.2); /* Sombra para darle profundidad */
}

input.form-control {
    border: 2px solid green; /* Borde verde */
    border-radius: 15px; /* Bordes redondeados */
    outline: none; /* Eliminar el outline predeterminado */
}

input.form-control:focus {
    border: 2px solid green; /* Mantener el borde verde al enfocar */
    border-radius: 15px; /* Mantener los bordes redondeados al enfocar */
    box-shadow: 0 0 5px rgba(0, 128, 0, 0.5); /* Outline verde */
}
</style>

Fase 2/Evidencias del proyecto/Evidencias de sistema/naturalworld_d/templates/admin_productos.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Administración de productos</title>
    <link rel="shortcut icon" href="{% static 'img/Logo_principal.png' %}">
    <!-- Enlace a Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Estilos personalizados -->
    <style>
        .borde-verde-redondeado {
            border: 2px solid green;   /* Borde verde */
            border-radius: 10px;       /* Esquinas redondeadas */
            padding: 15px;             /* Espacio interno opcional */
        }
        .tabla-personalizada th,
        .tabla-personalizada td {
            color: black;
        }
        .imagen-centrada {
            height: 50px;
            width: 50px;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
        
    </style>
<style>
    .bg-light-green {
        background-color: #c5eec8; /* Fondo claro */
    }

    @media (max-width: 768px) {
        h1 {
            font-size: 1.8em; /* Reducir el tamaño de la fuente en pantallas pequeñas */
        }
    }

    @media (min-width: 768px) {
        h1 {
            font-size: 2.5em; /* Tamaño normal para pantallas medianas y superiores */
        }
    }
</style>
</head>
<body>
    <br><br>
    {% if perms.app.add_Producto %}
    <div style="margin-left: 1%; margin-right: 1%;">
        <div class="container-fluid borde-verde-redondeado my-4">
            <a href="{% url 'index' %}" class="btn btn-outline-success mb-4">Volver al Inicio</a> 
            <div class="container mt-4">
                <h1 class="text-center bg-light-green py-3 px-4 rounded shadow-lg">
                    Administración de Productos
                </h1>
            </div>
                    <p style="text-align: center; font-size: 120%; margin-top: 20px;">Como usuario administrador, puedes ver el listado de productos de la tienda. Además, puedes agregar, modificar y eliminar productos.
                        <br><br><a href="{% url 'admin_add_producto' %}" class="btn btn-outline-info mb-4">Agregar producto</a> 
                    </p> 
                    
                </div>
                
    <div class="container-fluid borde-verde-redondeado"><br>
        <div class="table-responsive">
            {% if producto %}
                <table class="table table-bordered table-hover tabla-personalizada">
                    <thead>
                        <tr>
                            <th>Imagen</th>
                            <th>Código</th>
                            <th>Nombre</th>
                            <th>Descripción</th>
                            <th>Precio</th>
                            <th>Tipo de Producto</th>
                            <th>Peso</th>
                            <th>Altura</th>
                            <th>Ancho</th>
                            <th>Largo</th>
                            <th>Valor declarado</th>
                            <th>Stock</th>
                            <th>Modificar o Eliminar</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for producto in producto %}
                        <tr>
                            <td><img src="{{ producto.imagen.url }}" class="imagen-centrada" alt="..."></td>
                            <td>{{ producto.id }}</td>
                            <td>{{ producto.nombre }}</td>
                            <td>{{ producto.descripcion }}</td>
                            <td>{{ producto.precio_formateado }}</td>
                            <td>{{ producto.tipo_producto }}</td>
                            <td>{{ producto.peso }} Kg</td>
                            <td>{{ producto.altura }} cm</td>
                            <td>{{ producto.ancho }} cm</td>
                            <td>{{ producto.largo }} cm</td>
                            <td>{{ producto.valor_declarado |format_currency }}</td>
                            <td>{{ producto.stock }}</td>
                            <td> <div class="d-flex justify-content-between"> 
                                <a href="{% url 'admin_mod_producto' producto.id %}" class="btn btn-outline-success me-2">Modificar</a> 
                                <a href="{% url 'delete_producto' producto.id %}" class="btn btn-danger" onclick="return confirm('¿Estás seguro de que deseas eliminar este producto?');">Eliminar</a> 
                            </div> 
                        </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No se encontraron productos.</p>
            {% endif %}
        </div>
    </div>
</div>
{% else %}
<div class="container-fluid borde-verde-redondeado">
<p style="text-align: center;">Usted no es un usuario administrador <br> 
    <a style="color: blue;" href="{% url 'index' %}">Volver al Inicio</a></p>
</div>
{% endif %}
<br><br><br>

    <!--script de sweat alert-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if messages %}
      {% for m in messages%}
        <script>
          Swal.fire({
            "title": "Felicitaciones",
            "text": "{{m}}",
            "icon": "success"
          })

        </script>
      {% endfor %}
    {% endif %}
    <!-- Enlaces a Bootstrap JS (opcional) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Fase 2/Evidencias del proyecto/Evidencias de sistema/naturalworld_d/templates/checkout_resumen.html
<!-- checkout_resumen.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- checkout_resumen.html -->
<h1>Resumen de Compra</h1>
<p>Producto: {{ producto.nombre }}</p>
<p>Precio: ${{ producto.precio }}</p>
<p>Costo de Envío: ${{ costo_envio }}</p>
<p>Total a Pagar: ${{ total }}</p>

<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Proceder al Pago</button>
</form>

{% endblock %}

Fase 2/Evidencias del proyecto/Evidencias de sistema/naturalworld_d/templates/confirmacion.html
<!-- confirmacion.html -->
{% extends 'base.html' %}

{% block content %}
<body class="bg-light">
    <div class="container d-flex justify-content-center align-items-center vh-100">
        <div class="card shadow-lg p-4" style="max-width: 500px;">
            <div class="card-body text-center">
                <h2 class="card-title text-success">{{ mensaje }}</h2>
                <p class="card-text mt-3">Gracias por tu compra. Te hemos enviado un correo de confirmación.</p>
                <a href="{% url 'index' %}" class="btn btn-outline-success mt-4">Volver al Inicio</a>
            </div>
        </div>
    </div>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    </body>
{% endblock %}

Fase 2/Evidencias del proyecto/Evidencias de sistema/naturalworld_d/templates/confirmacion_envio.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>Confirmación de Envío</h1>
    <p>Producto: {{ producto.nombre }}</p>
    <p>Estado del Envío: {{ resultado_envio.status }}</p>
    <p>Número de Seguimiento: {{ resultado_envio.trackingNumber }}</p>
    <!-- Mostrar más detalles según la estructura de la respuesta de la API -->
</div>
{% endblock %}